version: '3.8'
services:
  db:
    image: postgres:15.4
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - '5432:5432'