spring:
  profiles:
    group:
      # "local" 프로파일이 활성화될 때, "common" 프로파일도 함께 활성화됩니다.
      # 로컬 환경에서 공통 설정을 적용하기 위해 사용됩니다.
      "local": "common"

      # "dev" 프로파일이 활성화될 때, "common" 프로파일도 함께 활성화됩니다.
      # 개발 환경에서 공통 설정을 적용하기 위해 사용됩니다.
      "dev": "common"

      # "prod" 프로파일이 활성화될 때, "common" 프로파일도 함께 활성화됩니다.
      # 운영 환경에서 공통 설정을 적용하기 위해 사용됩니다.
      "prod": "common"

      # "test" 프로파일이 활성화될 때, "common" 프로파일도 함께 활성화됩니다.
      # 테스트 환경에서 공통 설정을 적용하기 위해 사용됩니다.
      "test": "common"